package guiaplicationtest;

import java.awt.Color;

/**
 *
 * @author Aurelio Martinez Copyright. 2018
 */
public class mainFrame extends javax.swing.JFrame {

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        // Setting the background color of the main panel to white.
        jmainPanel.setBackground(Color.white);   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPicture = new javax.swing.JLabel();
        jmainPanel = new javax.swing.JPanel();
        jTextLabel = new javax.swing.JLabel();
        jContinueFrameButton = new javax.swing.JButton();
        jCopyrightLabel = new javax.swing.JLabel();
        jBuildRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Martinez Machines Bussiness Software");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabelPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiaplicationtest/LogoReducedCopy.JPG"))); // NOI18N

        jTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextLabel.setText("We give you the opportunity to build the computer of your dreams. ");

        jContinueFrameButton.setText("Continue");
        jContinueFrameButton.setEnabled(false);
        jContinueFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jContinueFrameButtonActionPerformed(evt);
            }
        });

        jCopyrightLabel.setText("© Aurelio Martinez ");

        jBuildRadioButton.setText("Build PC");
        jBuildRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuildRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jmainPanelLayout = new javax.swing.GroupLayout(jmainPanel);
        jmainPanel.setLayout(jmainPanelLayout);
        jmainPanelLayout.setHorizontalGroup(
            jmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmainPanelLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jContinueFrameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jmainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jmainPanelLayout.createSequentialGroup()
                        .addComponent(jBuildRadioButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jmainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jCopyrightLabel)))
                .addContainerGap())
        );
        jmainPanelLayout.setVerticalGroup(
            jmainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmainPanelLayout.createSequentialGroup()
                .addComponent(jTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBuildRadioButton)
                .addGap(8, 8, 8)
                .addComponent(jContinueFrameButton)
                .addGap(18, 18, 18)
                .addComponent(jCopyrightLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPicture)
            .addComponent(jmainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jmainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jContinueFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jContinueFrameButtonActionPerformed
        // Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsFrame().setVisible(true);                
            }
        });
    }//GEN-LAST:event_jContinueFrameButtonActionPerformed

    private void jBuildRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuildRadioButtonActionPerformed
        // If WindowsRB is selected, enabled the continue button.
        if(jBuildRadioButton.isSelected()) {
            jContinueFrameButton.setEnabled(true);            
        }
        
        if(!jBuildRadioButton.isSelected()) {
            jContinueFrameButton.setEnabled(false);            
        }
    }//GEN-LAST:event_jBuildRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton jBuildRadioButton;
    private javax.swing.JButton jContinueFrameButton;
    private javax.swing.JLabel jCopyrightLabel;
    private javax.swing.JLabel jLabelPicture;
    private javax.swing.JLabel jTextLabel;
    private javax.swing.JPanel jmainPanel;
    // End of variables declaration//GEN-END:variables
}
