/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiaplicationtest;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aurel
 */

// Creating a class customer.
class customer {
    // Variables.
    String fullName;
    String phoneNumber;
    String operativeSystemWindows;
    String operativeSystemWindowsServer;
    String processorBrandIntel;
    String processorBrandAmd;
    String ramSlots;    
    String ramAmount;
    String hardDriveStorage;
    String solidDriveStorage;
    String videoCard;
    String displayInches;
    String displayResolution;
    boolean wantsSpeakers;
    boolean wantsKeyboard;
    boolean wantsMouse;
    
    String comments;
    
    // Constructor.
    public customer(String fullName, String phoneNumber, String operativeSystemWindows, String operativeSystemWindowsServer, 
            String processorBrandIntel, String processorBrandAmd, String ramSlots, String ramAmount, String hardDriveStorage,
            String solidDriveStorage, String videoCard, String displayInches, String displayResolution, boolean wantsSpeakers,
            boolean wantsKeyboard, boolean wantsMouse, String comments) {
        this.fullName = fullName;
        this.phoneNumber = phoneNumber;
        this.operativeSystemWindows = operativeSystemWindows;
        this.operativeSystemWindowsServer = operativeSystemWindowsServer;
        this.processorBrandIntel = processorBrandIntel;
        this.processorBrandAmd = processorBrandAmd;
        this.ramSlots = ramSlots;
        this.ramAmount = ramAmount;
        this.hardDriveStorage = hardDriveStorage;
        this.solidDriveStorage = solidDriveStorage;
        this.videoCard = videoCard;
        this.displayInches = displayInches;
        this.displayResolution = displayResolution;
        this.wantsSpeakers = wantsSpeakers;
        this.wantsKeyboard = wantsKeyboard;
        this.wantsMouse = wantsMouse;        
        this.comments = comments;
    }
    
    // To String.
    @Override
    public String toString() {
        return "Customer: " + fullName + "\nPhone Number: " + phoneNumber + "\nOperative System Windows: " + operativeSystemWindows
                + "\nOperative System Windows Server: " + operativeSystemWindowsServer + "\nProcessor Brand Intel: " + processorBrandIntel 
                + "\nProcessor Brand AMD: " + processorBrandAmd + "\nRAM slots: " + ramSlots + "  RAM Amount: " + ramAmount 
                + "\nHard Drive Storage: " + hardDriveStorage + "\nSolid State Drive Storage: " + solidDriveStorage 
                + "\nVideo Card: " + videoCard + "\nDisplay Inches: " + displayInches + "   Display Resolution: " + displayResolution 
                + "\nDoes the costumer want ergonomic speakers?: " + wantsSpeakers + "\nDoes the costumer want ergonomic keyboard?: " + wantsKeyboard
                + "\nDoes the costumer want ergonomic mouse?: " + wantsMouse + "\n***Comments:***\n"+ comments +"\n" + "----------------------------------------------------------------------------------\n";
    }    
    
}

public class WindowsFrame extends javax.swing.JFrame {
    // Creating and ArrayList to save all customer objects.
    ArrayList<customer> arrayList;         
        
    /**
     * Creates new form WindowsFrame
     */
    public WindowsFrame() {
        initComponents();
        
        // Creating a new ArrayList Object.
        arrayList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPanel = new javax.swing.JTabbedPane();
        jFormPanel = new javax.swing.JPanel();
        jPersonalInformationLabel = new javax.swing.JLabel();
        jNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jNamePanel = new javax.swing.JTextPane();
        jCellphoneLabel = new javax.swing.JLabel();
        jPhoneText = new javax.swing.JTextField();
        jOperativeSystemLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jOsWindowsComboBox = new javax.swing.JComboBox<>();
        jOsWindowsRadioButton = new javax.swing.JRadioButton();
        jOsWindowsServerRadioButton = new javax.swing.JRadioButton();
        jOsWindowsServerComboBox = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jProcessorLabel = new javax.swing.JLabel();
        jIntelRadioButton = new javax.swing.JRadioButton();
        jAmdRadioButton = new javax.swing.JRadioButton();
        jIntelComboBox = new javax.swing.JComboBox<>();
        jAmdComboBox = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jRamLabel = new javax.swing.JLabel();
        jManyRamLabel = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jAmountRamLabel = new javax.swing.JLabel();
        jAmountRamComboBox = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jDriveLabel = new javax.swing.JLabel();
        jHardDriveRadioButton = new javax.swing.JRadioButton();
        jSolidDriveRadioButton = new javax.swing.JRadioButton();
        jHardDriveComboBox = new javax.swing.JComboBox<>();
        jSolidStateDriveComboBox = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jVideoCardLabel = new javax.swing.JLabel();
        jVideoCardComboBox = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jDisplayInchesLabel = new javax.swing.JLabel();
        jDisplayInchesComboBox = new javax.swing.JComboBox<>();
        jDisplayResolutionLabel = new javax.swing.JLabel();
        jDisplayResolutionComboBox = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jExtrasLabel = new javax.swing.JLabel();
        jHomeTheatherCheckBox = new javax.swing.JCheckBox();
        jErgonomicKeyboardCheckBox = new javax.swing.JCheckBox();
        jErgonomicMouseCheckBox = new javax.swing.JCheckBox();
        jSeparator8 = new javax.swing.JSeparator();
        jCommentsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCommentsArea = new javax.swing.JTextArea();
        jProcessOrderButton = new javax.swing.JButton();
        jDataPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jDataTextArea = new javax.swing.JTextArea();
        jDataLoadButton = new javax.swing.JButton();
        jDataClearButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPersonalInformationLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPersonalInformationLabel.setText("Enter your personal Information:");

        jNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNameLabel.setText("Enter your full name:");

        jScrollPane1.setViewportView(jNamePanel);

        jCellphoneLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCellphoneLabel.setText("Enter your phone number:");

        jOperativeSystemLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jOperativeSystemLabel.setText("Choose your Operative System:");

        jOsWindowsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Windows 10", "Windows 8.1", "Windows 8", "Windows 7", "Windows Vista", "Windows XP", "Windows 2000", "Windows 98", " " }));
        jOsWindowsComboBox.setEnabled(false);

        buttonGroup1.add(jOsWindowsRadioButton);
        jOsWindowsRadioButton.setText("Windows");
        jOsWindowsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOsWindowsRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(jOsWindowsServerRadioButton);
        jOsWindowsServerRadioButton.setText("Windows Server");
        jOsWindowsServerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOsWindowsServerRadioButtonActionPerformed(evt);
            }
        });

        jOsWindowsServerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Windows Server 2003", "Windows Home Server", "Windows Server 2008", "Windows Home Server 2001", "Windows Server 2012", "Windows Server 2016" }));
        jOsWindowsServerComboBox.setEnabled(false);

        jProcessorLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jProcessorLabel.setText("Choose your Processor Brand:");

        buttonGroup2.add(jIntelRadioButton);
        jIntelRadioButton.setText("Intel");
        jIntelRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntelRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(jAmdRadioButton);
        jAmdRadioButton.setText("AMD");
        jAmdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAmdRadioButtonActionPerformed(evt);
            }
        });

        jIntelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Intel Core i9 Extreme", "Intel Core i7 8th Gen", "Intel Core i5 8th Gen", "Intel Core i3 8th Gen" }));
        jIntelComboBox.setEnabled(false);
        jIntelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntelComboBoxActionPerformed(evt);
            }
        });

        jAmdComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "AMD Ryzen ", "AMD FX", "AMD Athlon", "AMD A-Series " }));
        jAmdComboBox.setEnabled(false);

        jRamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRamLabel.setText("Choose your Random Access Memory:");

        jManyRamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jManyRamLabel.setText("How many slots do you have:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 4, 2));

        jAmountRamLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAmountRamLabel.setText("Select the amount of RAM:");

        jAmountRamComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1 GB ", "2 GB", "4 GB", "8 GB", "16 GB", "32 GB", "64 GB" }));

        jDriveLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDriveLabel.setText("Select what kind of storage drive:");

        buttonGroup3.add(jHardDriveRadioButton);
        jHardDriveRadioButton.setText("Hard Drive");
        jHardDriveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHardDriveRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup3.add(jSolidDriveRadioButton);
        jSolidDriveRadioButton.setText("Solid State Drive");
        jSolidDriveRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSolidDriveRadioButtonActionPerformed(evt);
            }
        });

        jHardDriveComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB", "2 TB", "4 TB", "8 TB", "16 TB", "32 TB" }));
        jHardDriveComboBox.setEnabled(false);

        jSolidStateDriveComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "64 GB", "128 GB", "256 GB", "512 GB", "1 TB", "2 TB", "4 TB", "8 TB", "16 TB", "32 TB" }));
        jSolidStateDriveComboBox.setEnabled(false);

        jVideoCardLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jVideoCardLabel.setText("Select your video card:");

        jVideoCardComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Nvidia Geforce GTX 1060", "Nvidia Geforce GTX 1070", "Nvidia Geforce GTX 1080", "Nvidia Geforce Titan" }));

        jDisplayInchesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDisplayInchesLabel.setText("Select your display inches:");

        jDisplayInchesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "22'", "23'", "24'", "26'", "27'", "30'", "32'", "36'", "40'" }));

        jDisplayResolutionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jDisplayResolutionLabel.setText("Resolution:");

        jDisplayResolutionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "1024 x 768", "1024 x 768", "1280 x 768", "1280 x 1024\t", "1680 x 1050", "1920 x 1080", "2560 x 1600", "3840 x 2400" }));

        jExtrasLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jExtrasLabel.setText("Extras:");

        jHomeTheatherCheckBox.setText("Home Theater Speakers");

        jErgonomicKeyboardCheckBox.setText("Ergonomic Keyboard");

        jErgonomicMouseCheckBox.setText("Ergonomic Mouse");

        jCommentsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCommentsLabel.setText("Comments:");

        jCommentsArea.setColumns(20);
        jCommentsArea.setRows(5);
        jCommentsArea.setToolTipText("");
        jScrollPane2.setViewportView(jCommentsArea);

        jProcessOrderButton.setText("Process Order");
        jProcessOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProcessOrderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFormPanelLayout = new javax.swing.GroupLayout(jFormPanel);
        jFormPanel.setLayout(jFormPanelLayout);
        jFormPanelLayout.setHorizontalGroup(
            jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addComponent(jSeparator5)
            .addComponent(jSeparator6)
            .addComponent(jSeparator7)
            .addComponent(jSeparator8)
            .addGroup(jFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFormPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jFormPanelLayout.createSequentialGroup()
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNameLabel)
                            .addComponent(jPersonalInformationLabel)
                            .addComponent(jCellphoneLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPhoneText)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jFormPanelLayout.createSequentialGroup()
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jOperativeSystemLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jOsWindowsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jOsWindowsComboBox, 0, 148, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jOsWindowsServerRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jOsWindowsServerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9))
                    .addGroup(jFormPanelLayout.createSequentialGroup()
                        .addComponent(jProcessorLabel)
                        .addGap(31, 31, 31)
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIntelRadioButton)
                            .addComponent(jIntelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jAmdRadioButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jAmdComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jFormPanelLayout.createSequentialGroup()
                        .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRamLabel)
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jManyRamLabel)
                                    .addComponent(jAmountRamLabel))
                                .addGap(34, 34, 34)
                                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jAmountRamComboBox, 0, 83, Short.MAX_VALUE)
                                    .addComponent(jSpinner1)))
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jDriveLabel)
                                .addGap(18, 18, 18)
                                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jHardDriveComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jHardDriveRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(71, 71, 71)
                                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSolidDriveRadioButton)
                                    .addComponent(jSolidStateDriveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jVideoCardLabel)
                                .addGap(77, 77, 77)
                                .addComponent(jVideoCardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jDisplayInchesLabel)
                                .addGap(53, 53, 53)
                                .addComponent(jDisplayInchesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jDisplayResolutionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jDisplayResolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jExtrasLabel)
                            .addGroup(jFormPanelLayout.createSequentialGroup()
                                .addComponent(jHomeTheatherCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jErgonomicKeyboardCheckBox)
                                .addGap(27, 27, 27)
                                .addComponent(jErgonomicMouseCheckBox))
                            .addComponent(jCommentsLabel))
                        .addGap(0, 55, Short.MAX_VALUE))))
            .addGroup(jFormPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jProcessOrderButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jFormPanelLayout.setVerticalGroup(
            jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPersonalInformationLabel)
                .addGap(11, 11, 11)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCellphoneLabel)
                    .addComponent(jPhoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOperativeSystemLabel)
                    .addComponent(jOsWindowsRadioButton)
                    .addComponent(jOsWindowsServerRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jOsWindowsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOsWindowsServerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProcessorLabel)
                    .addComponent(jIntelRadioButton)
                    .addComponent(jAmdRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jIntelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAmdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRamLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jManyRamLabel)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAmountRamLabel)
                    .addComponent(jAmountRamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDriveLabel)
                    .addComponent(jHardDriveRadioButton)
                    .addComponent(jSolidDriveRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHardDriveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSolidStateDriveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVideoCardLabel)
                    .addComponent(jVideoCardComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDisplayInchesLabel)
                    .addComponent(jDisplayInchesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDisplayResolutionLabel)
                    .addComponent(jDisplayResolutionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jExtrasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHomeTheatherCheckBox)
                    .addComponent(jErgonomicKeyboardCheckBox)
                    .addComponent(jErgonomicMouseCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCommentsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jProcessOrderButton)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("Windows Form", jFormPanel);

        jDataTextArea.setColumns(20);
        jDataTextArea.setRows(5);
        jScrollPane3.setViewportView(jDataTextArea);

        jDataLoadButton.setText("Load Information");
        jDataLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataLoadButtonActionPerformed(evt);
            }
        });

        jDataClearButton.setText("Clear Information");
        jDataClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDataClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDataPanelLayout = new javax.swing.GroupLayout(jDataPanel);
        jDataPanel.setLayout(jDataPanelLayout);
        jDataPanelLayout.setHorizontalGroup(
            jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDataPanelLayout.createSequentialGroup()
                .addGroup(jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDataPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDataPanelLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDataLoadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDataClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jDataPanelLayout.setVerticalGroup(
            jDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jDataLoadButton)
                .addGap(18, 18, 18)
                .addComponent(jDataClearButton)
                .addContainerGap(461, Short.MAX_VALUE))
        );

        jTabbedPanel.addTab("Data", jDataPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jOsWindowsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOsWindowsRadioButtonActionPerformed
        // If WindowsRB is selected, disabled the windows server one.
        if(jOsWindowsRadioButton.isSelected()) {
            jOsWindowsComboBox.setEnabled(true);
            jOsWindowsServerComboBox.setSelectedItem("None");
            jOsWindowsServerComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jOsWindowsRadioButtonActionPerformed

    private void jOsWindowsServerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOsWindowsServerRadioButtonActionPerformed
        // If WindowsServerRB is selected, disabled the windows one.
        if(jOsWindowsServerRadioButton.isSelected()) {
            jOsWindowsServerComboBox.setEnabled(true);
            jOsWindowsComboBox.setSelectedItem("None");
            jOsWindowsComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jOsWindowsServerRadioButtonActionPerformed

    private void jIntelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntelComboBoxActionPerformed
        
    }//GEN-LAST:event_jIntelComboBoxActionPerformed

    private void jAmdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAmdRadioButtonActionPerformed
        // If AmdRB is selected, disabled the Intel one.
        if(jAmdRadioButton.isSelected()) {
            jAmdComboBox.setEnabled(true);
            jIntelComboBox.setSelectedItem("None");
            jIntelComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jAmdRadioButtonActionPerformed

    private void jIntelRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntelRadioButtonActionPerformed
        // If IntelRB is selected, disabled the AMD one.
        if(jIntelRadioButton.isSelected()) {
            jIntelComboBox.setEnabled(true);
            jAmdComboBox.setSelectedItem("None");
            jAmdComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jIntelRadioButtonActionPerformed

    private void jHardDriveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHardDriveRadioButtonActionPerformed
        // If HDRB is selected, disabled the SSD one.
        if(jHardDriveRadioButton.isSelected()) {
            jHardDriveComboBox.setEnabled(true);
            jSolidStateDriveComboBox.setSelectedItem("None");
            jSolidStateDriveComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jHardDriveRadioButtonActionPerformed

    private void jSolidDriveRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSolidDriveRadioButtonActionPerformed
        // If SSDRB is selected, disabled the HD one.
        if(jSolidDriveRadioButton.isSelected()) {
            jSolidStateDriveComboBox.setEnabled(true);
            jHardDriveComboBox.setSelectedItem("None");
            jHardDriveComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_jSolidDriveRadioButtonActionPerformed

    private void jProcessOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProcessOrderButtonActionPerformed
        // Events that happen when you click the button.
        
        // Adding the name to the object and array list.
        arrayList.add(new customer(jNamePanel.getText(), jPhoneText.getText(), jOsWindowsComboBox.getSelectedItem().toString(),
        jOsWindowsServerComboBox.getSelectedItem().toString(), jIntelComboBox.getSelectedItem().toString(), jAmdComboBox.getSelectedItem().toString(),
        jSpinner1.getValue().toString(), jAmountRamComboBox.getSelectedItem().toString(), jHardDriveComboBox.getSelectedItem().toString(),
        jSolidStateDriveComboBox.getSelectedItem().toString(), jVideoCardComboBox.getSelectedItem().toString(), jDisplayInchesComboBox.getSelectedItem().toString(),
        jDisplayResolutionComboBox.getSelectedItem().toString(), jHomeTheatherCheckBox.isSelected(), jErgonomicKeyboardCheckBox.isSelected(), jErgonomicMouseCheckBox.isSelected(),
        jCommentsArea.getText()));
        
        // Creating a file to write all the information.
        try {
            // Creating a file.    
            PrintWriter outputFile = new PrintWriter("info.txt");
            for(customer s: arrayList) {
                outputFile.write(s.toString());
            }
            outputFile.close();            
        } catch (FileNotFoundException e) {
            // In case that file wasn't read.
            JOptionPane.showMessageDialog(null, "Your file couldn't be read.");
        }
        
        // Show a pop-up message to show that order was successfully received.
        JOptionPane.showMessageDialog(null, "Your order was sucessfully completed.");
        
        // Setting everything back to normal.
        jNamePanel.setText("");
        jPhoneText.setText("");
        buttonGroup1.clearSelection();
        jOsWindowsComboBox.setSelectedIndex(0);
        jOsWindowsComboBox.setEnabled(false);
        jOsWindowsServerComboBox.setSelectedIndex(0);
        jOsWindowsServerComboBox.setEnabled(false);
        buttonGroup2.clearSelection();
        jIntelComboBox.setSelectedIndex(0);
        jIntelComboBox.setEnabled(false);        
        jAmdComboBox.setSelectedIndex(0);
        jAmdComboBox.setEnabled(false);                
        jSpinner1.setValue(0);
        jAmountRamComboBox.setSelectedIndex(0);
        buttonGroup3.clearSelection();
        jHardDriveComboBox.setSelectedIndex(0);
        jHardDriveComboBox.setEnabled(false);
        jSolidStateDriveComboBox.setSelectedIndex(0);
        jSolidStateDriveComboBox.setEnabled(false);
        jVideoCardComboBox.setSelectedIndex(0);
        jDisplayInchesComboBox.setSelectedIndex(0);
        jDisplayResolutionComboBox.setSelectedIndex(0);
        jHomeTheatherCheckBox.setSelected(false);
        jErgonomicKeyboardCheckBox.setSelected(false);
        jErgonomicMouseCheckBox.setSelected(false);
        jCommentsArea.setText("");                       
                
    }//GEN-LAST:event_jProcessOrderButtonActionPerformed

    private void jDataLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataLoadButtonActionPerformed
        // Events that happen when you click the button.
        try {
            // word counter
            FileReader fileReader = new FileReader("info.txt");
            // Scanner scanner = new Scanner(fileReader);
            
            String readFile = new Scanner(new File("info.txt")).useDelimiter("\\A").next(); 
            
            // while(scanner.hasNext()){
                // jDataTextArea.setText(scanner.nextLine());                
            // }
            
            jDataTextArea.setText(readFile); 
            
        } catch (FileNotFoundException ex) {
            // In case that file wasn't loaded.
            JOptionPane.showMessageDialog(null, "Your file couldn't be loaded.");
        }
        
        // Show a pop-up message to show that order was successfully received.
        JOptionPane.showMessageDialog(null, "All information was sucessfully loaded from the document.");
    }//GEN-LAST:event_jDataLoadButtonActionPerformed

    private void jDataClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDataClearButtonActionPerformed
        // Events that happen when you click the button.
        jDataTextArea.setText("");
    }//GEN-LAST:event_jDataClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {   
            
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowsFrame().setVisible(true);
            }
        });
         */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> jAmdComboBox;
    private javax.swing.JRadioButton jAmdRadioButton;
    private javax.swing.JComboBox<String> jAmountRamComboBox;
    private javax.swing.JLabel jAmountRamLabel;
    private javax.swing.JLabel jCellphoneLabel;
    private javax.swing.JTextArea jCommentsArea;
    private javax.swing.JLabel jCommentsLabel;
    private javax.swing.JButton jDataClearButton;
    private javax.swing.JButton jDataLoadButton;
    private javax.swing.JPanel jDataPanel;
    private javax.swing.JTextArea jDataTextArea;
    private javax.swing.JComboBox<String> jDisplayInchesComboBox;
    private javax.swing.JLabel jDisplayInchesLabel;
    private javax.swing.JComboBox<String> jDisplayResolutionComboBox;
    private javax.swing.JLabel jDisplayResolutionLabel;
    private javax.swing.JLabel jDriveLabel;
    private javax.swing.JCheckBox jErgonomicKeyboardCheckBox;
    private javax.swing.JCheckBox jErgonomicMouseCheckBox;
    private javax.swing.JLabel jExtrasLabel;
    private javax.swing.JPanel jFormPanel;
    private javax.swing.JComboBox<String> jHardDriveComboBox;
    private javax.swing.JRadioButton jHardDriveRadioButton;
    private javax.swing.JCheckBox jHomeTheatherCheckBox;
    private javax.swing.JComboBox<String> jIntelComboBox;
    private javax.swing.JRadioButton jIntelRadioButton;
    private javax.swing.JLabel jManyRamLabel;
    private javax.swing.JLabel jNameLabel;
    private javax.swing.JTextPane jNamePanel;
    private javax.swing.JLabel jOperativeSystemLabel;
    private javax.swing.JComboBox<String> jOsWindowsComboBox;
    private javax.swing.JRadioButton jOsWindowsRadioButton;
    private javax.swing.JComboBox<String> jOsWindowsServerComboBox;
    private javax.swing.JRadioButton jOsWindowsServerRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPersonalInformationLabel;
    private javax.swing.JTextField jPhoneText;
    private javax.swing.JButton jProcessOrderButton;
    private javax.swing.JLabel jProcessorLabel;
    private javax.swing.JLabel jRamLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JRadioButton jSolidDriveRadioButton;
    private javax.swing.JComboBox<String> jSolidStateDriveComboBox;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPanel;
    private javax.swing.JComboBox<String> jVideoCardComboBox;
    private javax.swing.JLabel jVideoCardLabel;
    // End of variables declaration//GEN-END:variables
}
